name: Daily Update

on:
  schedule:
    - cron: '3 0 * * *'
  workflow_dispatch:

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update code
        run: |
          echo "Update content $(date)" >> update.txt
          git add .
          git commit -m "Daily update $(date)"
          git push
