name: Daily Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update code
        run: |
          git config --global user.name "thamatis"
          git config --global user.email "thamatis1@gmail.com"
          echo "Update content $(date)" >> update.txt
          git add .
          git commit -m "Daily update $(date)"
          git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }} \
            --force --quiet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
